name: student_dashboard
description: A minimal review snapshot of the student_dashboard app.
publish_to: 'none'
version: 1.0.0
environment:
  sdk: '>=2.17.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
